#!/usr/bin/env bash
# Creates an RSA key pair named 'school' with 4096 bits, passphrase 'betty'
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty" -C "intranet project" 

# we can add -q flag (quite) meaning no output will be displayed usual scenario in automating tasks

