#!/usr/bin/env bash
#installing Nginx and configuring it
sudo apt update -y # update package manager to get the latest updates when installing nginx.
sudo apt install nginx -y # install nginx
new_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
		root /var/www/html;
	index index.html index.html index.nginx-debian.html;
	server_name _;
	add_header X-Served-By $HOSTNAME;
}
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default # change ownership
echo "$new_config" > /etc/nginx/sites-available/default # overwrite the existing configuration
sudo service nginx restart # restart the nginx