#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm

# Update system and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Backup the original haproxy.cfg in case something goes wrong
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Check if the configuration for frontend and backend exists
if ! grep -q "frontend tj-frontend" /etc/haproxy/haproxy.cfg; then
    # Add frontend and backend configuration
    server_config="frontend tj-frontend
        bind *:80
        mode http
        default_backend tj-backend

    backend tj-backend
        balance roundrobin
        server 6386-web-01 44.202.1.224:80 check
        server 6386-web-02 3.91.57.170:80 check"
    
    # Append the configuration to haproxy.cfg
    echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
else
    echo "Frontend and Backend configuration already exists in haproxy.cfg."
fi

# Enable HAProxy to start on boot
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

