#!/usr/bin/env bash
# Installs and configures Nginx to serve a static html page with a texy "Holberton School for the win!"

# Update package list (we use apt-get as it is legacy and helps in maintaining old versions unlike the latest apt)
apt-get update

# Install Nginx (-y makes it non-interactive as we are automating the process)
apt-get install -y nginx

# Create custom page (simple index.html) which overtakes the default nginx page
echo "Holberton School for the win!" > /var/www/html/index.html

chmod 644 /var/www/html/index.html

# Ensure Nginx listens on port 80 (default config should already do this but for safeguard)
# But let's be explicit
sed -i 's/^\s*listen .*/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sed -i 's/^\s*listen \[::\]:.*/listen [::]:80 default_server;/g' /etc/nginx/sites-enabled/default

# Restart Nginx (using command other than systemctl) 
service nginx restart

# Or: /etc/init.d/nginx restart
